name: Build PrimeGram IPA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4
      - name: Try import
        run: |
          python3 build-system/Make/ImportCertificates.py --path build-system/fake-codesigning/certs
